// Augment the global `Env` (generated by `wrangler types` into
// worker-configuration.d.ts) with secret fields. Secrets live on the
// platform (set via `wrangler secret put`) and aren't declared in
// wrangler.jsonc, so wrangler's type generator can't infer them.

declare global {
  interface Env {
    // USAJobs (Phase 1)
    USAJOBS_API_KEY?: string;
    USAJOBS_USER_AGENT?: string;

    // Daily digest (Phase 3)
    GITHUB_TOKEN?: string;
    DIGEST_REPO?: string;

    // Alerts + optional HTTP API (Phase 4)
    DISCORD_WEBHOOK_URL?: string;
    API_TOKEN?: string;
  }
}

export {};
