// Augment the global `Env` (generated by `wrangler types` into
// worker-configuration.d.ts) with secret fields. Secrets live on the
// platform (set via `wrangler secret put`) and aren't declared in
// wrangler.jsonc, so wrangler's type generator can't infer them.

declare global {
  interface Env {
    USAJOBS_API_KEY?: string;
    USAJOBS_USER_AGENT?: string;
    ADZUNA_APP_ID?: string;
    ADZUNA_APP_KEY?: string;
    GITHUB_TOKEN?: string;
    DIGEST_REPO?: string;
    DISCORD_WEBHOOK_URL?: string;
    API_TOKEN?: string;
  }
}

export {};
